version: '3.4'

services:
  db:
     image: rest-with-asp-net-5
     command: mysqld --default-authentication-plugin=mysql_native_password
     restart: always
     build:
       context: .
       dockerfile: db/Dockerfile
     environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_USER: docker
       MYSQL_PASSWORD: docker
       MYSQL_DATABASE: rest_with_asp_net
     ports:
       - 3308:3306
     networks:
       - api-network

  rest-with-asp-net-5:
     image: rest_with_asp_net
     build:
        context: .
        dockerfile: RestWithASPNET5/Dockerfile
     environment:
       TZ: America/Sao_Paulo
       ASPNETCORE_ENVIRONMENT: Production
     ports:
       - 44300:80
     depends_on:
       - db
     networks:
       - api-network

networks:
  api-network:
    driver: bridge